### ISSUE TITLE
Make network analysis script multi-threaded

### ISSUE THREAD

**Issue by Ameobea** [Ameobea/network_research#14]
By multi-threading the network analysis script, it will be able to utilize multiple cores and perform many times faster.  Since python by default is locked to only one core and computers generally have many more (4 to 8, extending into several dozen for high-end servers), this change will make the script much more efficient for larger and more complex networks.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/118867524991974/136444338921406)

**Comment by Ameobea** [comment]
Unfortunately, python doesn't support running threads on multiple cores.  To get around this, I've decided to spawn other processes manually by executing them directly from the script itself without going through multiprocessing or any other library.  This should be the most multi-platform solution and serve as the best solution.

**Comment by Ameobea** [comment]
Python doesn't even support running threads on multiple cores in the same process.  To get around **this**, I've decided to simply spawn more processes manually by calling the python command from within a python script using the `subprocess` module.  

By doing this, I can asynchronously manage multiple workers at the same time and spawn more as needed without blocking the main thread.

This has been implemented in 46d891d5654cddc38ad5afddd62a43dbaa05b136

**Comment by lilsinger6690** [comment]
Thanks for all the work you're doing, sorry I can't help with anything
really.

AnnaLee

**Comment by Ameobea** [comment]
@lilsinger6690 this change was very highly technical and had nothing to do with network science or networks at all.  It was just a structural change to the way the script ran that involved lots of elements of rather advanced computer science.  

Having this done will make it easier to process networks and will allow you to get to doing actual network-related stuff sooner.  You'll have plenty of opportunities to help in the future :)
