### ISSUE TITLE
Use MatLab (possibly) to preform calculations quickly

### ISSUE THREAD

**Issue by Ameobea** [Ameobea/network_research#24]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/118867524991974/137605002201258)

**Comment by Pelonza** [comment]
I doubt MATLAB will be particularly faster after you have to import/export
things. python, using numpy and panda is pretty fast.

Karl Schmitt
Assistant Professor
Department of Mathematics and Statistics
Department of Computing and Information Sciences
Director of Analytics and Modeling Graduate Program
Valparaiso University, Indiana
